using UnityEngine;

public class MermiController : MonoBehaviour
{


    PlayerHealthController playerHealthController;

    void Awake()
    {
        playerHealthController = Object.FindAnyObjectByType<PlayerHealthController>();
    }

    public float mermiH覺z覺;

    private void Update()
    {
        transform.position += new Vector3(-mermiH覺z覺 * Time.deltaTime * transform.localScale.x, 0f, 0f);
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            playerHealthController.HasarAl();
        }

        Destroy(gameObject);
        
    }

}
